spring:
  application:
    name: Config-Default
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    resister-with-client: true
    service-url:
      defaultZone: http://localhost:8761/eureka
